### ISSUE TITLE
斷點續傳問題

### ISSUE THREAD

**Issue by lowfiend** [zhaozepeng/Android_framework#3]
在當前activity下載時按暫停都可以繼續上次暫停下載的size開始下載

但是在下載的途中，離開activity 造成manager.stop();之後

再次回到頁面按下載，他會重新下載並非從離開當時的size繼續。

查看code後，並無增加至sqlite中。

建議新增

**Comment by zhaozepeng** [comment]
好的，已经解决了，是数据库id的问题，非常感谢你

**Comment by lowfiend** [comment]
好哦，明天測。話說你的可以異步下載？或者有兩個以上連結的用法？

**Comment by zhaozepeng** [comment]
多线程的异步下载，可以同时下载多个文件

**Comment by lowfiend** [comment]
但是會引發onProgressChanged不同的問題?
我是沒試過，只是單單純問問。
你可以嘗試在sample變成兩個檔案下載看看，
因為昨天改了下載如果server不穩的時候會造成的問題，
怕如果是兩個檔案以上不知道會不會影響

**Comment by zhaozepeng** [comment]
用法就是新建两个FileDownloadManager对象，如果再多的话使用数组来管理就行，demo我已经上传了，试了一下，没什么问题，对了，因为数据库的结构修改了，所以最好卸载应用重新安装

**Comment by lowfiend** [comment]
有這我了解，但通常是改版的話建議可以加入onUpgrade ，只是給你個另個解答

我測試看看

**Comment by zhaozepeng** [comment]
对对对，这个我知道，只是太懒了，哈哈哈哈

**Comment by lowfiend** [comment]
我剛剛發現一個問題

就是出現斷線的時候這個會顯示
case FileDownloadManager.STATE_SERVER_ERROR:
 tv_state1.setText("服务器错误");

但是我等到
01-13 10:45:36.547 2600-2600/? I/[PID:2600]: [TID:1] ProgressChangeHandler.handleMessage(line:553): state9
01-13 10:45:36.547 2600-2842/? I/[PID:2600]: [TID:142] FileDownloadManager.stopStartThread(line:358): 开始线程还未结束
01-13 10:45:36.651 2600-2600/? I/[PID:2600]: [TID:1] ProgressChangeHandler.handleMessage(line:553): state3
01-13 10:45:36.751 2600-2600/? I/[PID:2600]: [TID:1] ProgressChangeHandler.handleMessage(line:553): state3
01-13 10:45:36.751 2600-2600/? I/[PID:2600]: [TID:1] ProgressChangeHandler.handleMessage(line:553): state4

state4傳送後底下卻沒實現

case FileDownloadManager.STATE_STOPED:
                        tv_state1.setText("停止成功");
                        break;

**Comment by zhaozepeng** [comment]
//如果在下载过程中网络发生错误，或者服务器发生错误，就不再更新后面的停止状态
if ((activityWeakReference.get().currentState == STATE_NET_ERROR
        || activityWeakReference.get().currentState == STATE_SERVER_ERROR)
        && (msg.what==STATE_STOPING || msg.what==STATE_STOPED)){
    return;
}
这个是我故意屏蔽的，因为我觉得服务器和网络错误应该是一种特殊的需要向用户展示的状态

**Comment by lowfiend** [comment]
哦哦 好的，好像沒啥問題了，那我的任務結束，再去尋找別的git

有需要測試在mail我吧
