### ISSUE TITLE
jsonObjectRequest的params   php取得不到

### ISSUE THREAD

**Issue by lowfiend** [zhaozepeng/Android_framework#4]
我android使用

` HashMap<String, String> params = new HashMap<String, String>();
        params.put("test","myAction");
        NetApi.getInstance().jsonObjectRequest(getActivity(), url, params,
                new BaseNetApi.OnNetCallback<JSONObject>() {
                    @Override
                    public void onSuccess(JSONObject result) {
                       
                        Log.e("test", result.toString());
                    }

                    @Override
                    public void onFail(NetError error) {
                        Log.e("test", error.errorMessage);
                    }
                });`

我php使用
$data = file_get_contents('php://input');
$json = json_decode($data);
$test = $json->{'test'};

$fp = fopen('output.txt', 'w');
fwrite($fp, $test);
fclose($fp);

一直為空

**Comment by zhaozepeng** [comment]
你有QQ么？？我加你QQ，那样交流方便一点，这个问题我不是太明白= =

**Comment by lowfiend** [comment]
有we chat

**Comment by zhaozepeng** [comment]
153436644，我的微信。话说你们也用微信？？

**Comment by zhaozepeng** [comment]
这个问题我貌似遇见过，我在BaseNetApi中使用的是静态内部类，但是静态内部类是有一个延迟加载操作的，所以这里的JsonObjectRequestImpl.class是可能没有值的，这个问题，稍后我去仔细看看

**Comment by lowfiend** [comment]
Wechat找不到你，我是都有用

Params 那個我是用你範例那個，只是我加入一些參數傳遞，結果php都沒收到

我的

**Comment by lowfiend** [comment]
low8004 wechatID

**Comment by lowfiend** [comment]
幫你解出來了

你的void少用new JSONObject(params)

改成這樣

  public JsonObjectRequestImpl(int method, String url, Response.Listener<JSONObject> listener,
                                 Response.ErrorListener errorListener, Map<String, String> params) {
            super(method, url,new JSONObject(params), listener, errorListener);
            this.params = params;
        }


php code:

$post = json_decode(file_get_contents("php://input"), true);
$xxx= $post['xxxx'];
$xxxxx= $post['xxxxx'];

就可以了
