### ISSUE TITLE
对此框架的一点猜测

### ISSUE THREAD

**Issue by limin13215** [zhaozepeng/Android_framework#5]
楼主太棒了，忍不住想跟楼主能达到一点共识，所以写了这点猜测： 楼主写的框架，是否有仿照android源生framework框架的意思， 只是您这个架构比较简单一些， 但是加入了当前一些流行的开源框架和个人编写应用的一些习惯，以便在实际应用中此框架能真正有所作为；

**Comment by lowfiend** [comment]
android技术交流 544645972  歡迎一起來討論

**Comment by limin13215** [comment]
进群了。
